version: '3.5'

services:

  mysql-db:
    image: mysql:5.7
    container_name: mysql_database
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/mysql-db:/var/lib/mysql
      - ./database/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
    networks:
      - interface_network
      - app_network
    env_file:
      - environment_hw2.env

  api_server:
    links:
      - mysql-db
    depends_on:
      - mysql-db
    build: ./src
    image: api_server_t2_img
    container_name: api_server_t2
    environment:
      MYSQL_PORT: 3306
    ports:
      - 5000:5000
    networks:
      - app_network
    env_file:
      - environment_hw2.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: web_admin
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    links:
      - mysql-db
    depends_on:
      - mysql-db
    networks:
      - interface_network

networks:
  app_network:
    name: app_network
  interface_network:
    name: interface_network

volumes:
  mysql-db:
    name: mysql-db
